version: "3"
services:
  test-runner:
    build:
      dockerfile: Build-Automation/System-Tests/Dockerfile
      context: ../../..
    container_name: test-runner
    command: ["npm", "run", "test:ci"]
    depends_on: ["test-wirtbot"]
    volumes:
      - ./test-Corefile:/tmp/WirtBotTests/Corefile
      - ./test-server.conf:/tmp/WirtBotTests/server.conf
  test-wirtbot:
    build:
      dockerfile: Build-Automation/WirtBot/Dockerfile
      context: ../../..
      args:
        - environment=test
    container_name: wirtbot.test
    volumes:
      - ./test-server.conf:/etc/wireguard/server.conf:z
      - ./test-Corefile:/etc/coredns/Corefile:z
    ports:
      - 10101:10101/udp
    environment:
      - "PUBLIC_KEY=1lLU3VhXsrSGMxESmqfY4m2oEVkpfEHyKlCQU6MMPsI="
      - "PORT=3030"
      - "ALLOWED_ORIGIN=http://wirtbot.test"
      - "RUST_LOG=debug"
      - "MANAGED_DNS_ENABLED=1"
      - "MANAGED_DNS_DEVICE_FILE=/etc/coredns/Corefile"
      - "CONFIG_PATH=/etc/wireguard/server.conf"

volumes:
  download_folder:
