version: "3"

services:
  wirtbot:
    build: 
      context: ../../..
      dockerfile: Build-Automation/WirtBot/DevDockerfile
    ports: [3030:3030]
    restart: always
    volumes: ["../..:/app"]
    environment:
      "PUBLIC_KEY": "1lLU3VhXsrSGMxESmqfY4m2oEVkpfEHyKlCQU6MMPsI="
      "ALLOWED_ORIGIN": "http://localhost:8080"
      "RUST_LOG": "debug"
      "MANAGED_DNS_ENABLED": 1
    cap_add:
      - NET_ADMIN
    volumes:
      - ./test-server.conf:/etc/wireguard/server.conf
      - ./test-Corefile:/dns/Corefile
    ports:
      - 10101:10101/udp
    container_name: development_wirtbot
