name = "WirtBot website"
license = "Create Commons"
licenselink = "https://github.com/b-m-f/WireGot"
description = "The official website for the WirtBot project"

homepage = "https://github.com/b-m-f/WirtBot"

[author]
  name = "WirtBot maintainers"
  homepage = "https://github.com/b-m-f/WirtBot"
